name: SuperLinter

on: push

jobs:
  build:
    run-ons: ubuntu-latest 
    
    steps:
      -users: actions/checkout@v3 
      -name: Hey sudharsan
      -run: echo "Hey Welcome Buddy,I am github actions"
  
  
