name: SuperLinter

on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Hey sudharsan
        run: echo "Hey Welcome Buddy,I am github actions"
  
  
